version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/app/mercury/django_static
            - media_volume:/app/mercury/media
            - ./docker/nginx/pro:/etc/nginx/conf.d
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        depends_on: 
            - mercury
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"       

    mercury:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/mercury/Dockerfile
            args:
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        entrypoint: /app/docker/mercury/entrypoint.sh
        volumes:
            - ${NOTEBOOKS_PATH}:/app/notebooks
            - static_volume:/app/mercury/django_static
            - media_volume:/app/mercury/media
        expose:
            - 8000     
        environment:
            DEBUG: ${DEBUG}
            SERVE_STATIC: ${SERVE_STATIC}
            DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
            DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
            DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
            SECRET_KEY: ${SECRET_KEY}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            WELCOME: ${WELCOME}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_HOST_USER: ${EMAIL_HOST_USER}
            EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
            EMAIL_PORT: ${EMAIL_PORT} 
            DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - db
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

volumes:
    static_volume: {}
    media_volume: {}
    postgres_data: {}
